package main

import (
	"fmt"
	"hash/crc32"
)

const (
	PartCount = 60
)

var uuids = []string{
	"15maTWbU",
	"25S1J3Pt",
	"2B8y3X6b",
	"2PiFQNKp",
	"2UE2fnhi",
	"2VpNDujL",
	"2YMPoa37",
	"2bY13bz1",
	"2dySdxtk",
	"2eQzrs6m",
	"2fTLnjZ5",
	"2iTpamXf",
	"2jW9Buvk",
	"2oNysuLY",
	"2vMDex9j",
	"2wSPJhMw",
	"2yQw95MP",
	"36Bp1Zth",
	"37Qypnk7",
	"39LqRuA3",
	"3Hve2WXX",
	"3MvcLbT7",
	"3PrHDmiw",
	"3UU5GrNN",
	"3UzS6id1",
	"3j27EFdy",
	"3mqdSsRg",
	"3s8TzxLN",
	"3x5Ncfhu",
	"4CE1jNG1",
	"4CyDd8Um",
	"4DbXh775",
	"4GApXTY7",
	"4H37CawX",
	"4MQR6XHH",
	"4S1iK6bc",
	"4TMAs7Ek",
	"4nRrkDm4",
	"4ox23XP1",
	"4uQWsydo",
	"51yPp7qy",
	"57QJRAnd",
	"57sd1Nr4",
	"59j6WGkt",
	"59wGAufD",
	"5Ldu1zBG",
	"5NRyWKAd",
	"5PG4tiL6",
	"5PpxqNv6",
	"5SpNermD",
	"5WwRWQeG",
	"5eqWAaZ4",
	"5h2LdozA",
	"5i64Qruj",
	"5jS5jZLE",
	"5jSogdFt",
	"5uPxtqfp",
	"5v6y2SgM",
	"5wZtqm3Y",
	"69EKFKKg",
	"6CWudchy",
	"6Dpbg2CT",
	"6GB9SD38",
	"6KXMU4me",
	"6KkDuVLm",
	"6M5aXWr1",
	"6RDuyk2r",
	"6Ud4i69f",
	"6YGdvUzR",
	"6b1xfuLt",
	"6btTpWQ8",
	"6mhCXCph",
	"6pFyibf1",
	"6s6VcAER",
	"71ebCRpp",
	"75RxVHdN",
	"7FASyKUm",
	"7JcZYetc",
	"7KBqrymN",
	"7LYF9zcr",
	"7Y2dmiNF",
	"7fAHGCTA",
	"7itocAvB",
	"7jBw5WGu",
	"7jeSB8Qs",
	"7qrNey6z",
	"7sXCDnjR",
	"7srA8w8G",
	"7tcwLZ1m",
	"7uuaVzT4",
	"8DAV12GD",
	"8HMoe9Z6",
	"8NDW5p9g",
	"8NmnR6e6",
	"8PmT2dna",
	"8Ra3P5wm",
	"8VqtZoFH",
	"8apkfv9y",
	"8d7AEqkq",
	"8hrfX3EW",
	"8wfrjik6",
	"94MN9YV7",
	"9AAL4Uxs",
	"9Aa3spC8",
	"9DYQ8Bod",
	"9P1frHyk",
	"9PhCjtiQ",
	"9Rxhjfzg",
	"9T1u26t1",
	"9WUuiBy8",
	"9Yfao3SF",
	"9ZSUF228",
	"9dkMzLbp",
	"9kQhVtYL",
	"9mW4CAW6",
	"9p17ggnz",
	"9pStXFg2",
	"9qyf1N2h",
	"9vSt3ARP",
	"9wXgsLot",
	"9xeXZa5z",
	"A1iGXQBF",
	"A1zTshH3",
	"A7zLc4a2",
	"AGSVjSaB",
	"AKtYjhef",
	"ANivjkNL",
	"AWjAYXZK",
	"AZcTfJ55",
	"Aej8Utvu",
	"AgxsFmgx",
	"AoMqQXVb",
	"AtWvx6De",
	"B4g4kKe9",
	"B5xq77yM",
	"B6kXsXBg",
	"B9est3vn",
	"B9mLJ4nH",
	"BDfDqJU7",
	"BHr1RMey",
	"BTw2PLu8",
	"BWZrAWsh",
	"BZRzbT74",
	"Bam7VXdk",
	"Bc3J5upA",
	"Be3a6vUJ",
	"BeixhuaZ",
	"Bk5uSwxU",
	"Bk6QUfpU",
	"BmbRN732",
	"BpfSPLdX",
	"BwKj4CDQ",
	"C3M7iEYP",
	"C6dNvUhY",
	"C8sA22zq",
	"CBqiNhSc",
	"CDRzkeQq",
	"CLrWkmKs",
	"CU4UxPru",
	"CgtLCN12",
	"CinDhpRQ",
	"CkNbMwF7",
	"CpvKf1c7",
	"CrLrVdaN",
	"CtoC9Wmj",
	"CwgpTpov",
	"CxCS4LjY",
	"CzZEoQkJ",
	"D3yRm3ke",
	"D6boFHJg",
	"D723HmsW",
	"DDSD5YJf",
	"DJuzkq3G",
	"DNi76CVC",
	"DR9XGtNB",
	"DaXf8REY",
	"DbGERkun",
	"DdjfEJhY",
	"DgZy69Lr",
	"Di74YhBo",
	"DkQrKUJc",
	"DmquKNst",
	"DnQP3K6j",
	"DnREV6bd",
	"DoCCEGr4",
	"DqBrdG2G",
	"DsAAeary",
	"DsMaiLeS",
	"Dviw3Bgr",
	"DwNuSydq",
	"E28nA8Vp",
	"E7zymNLK",
	"EE8A1jhr",
	"EFWL8xQm",
	"EG7mHtRB",
	"EKPU8fq1",
	"ENESMech",
	"EP8uM9VJ",
	"ESVDabVb",
	"ESWzYSXH",
	"EW8eiWTj",
	"EWuZVW9a",
	"EbmA7KH1",
	"Ee6SWqag",
	"EfZnza18",
	"EphwhPYt",
	"Ex73Xm6M",
	"F3FjFodp",
	"F4iudMJv",
	"F9fTr2Tu",
	"FDEMnho5",
	"FDnTv1GR",
	"FFbAkazs",
	"FLQeK76G",
	"FRZd9JXu",
	"FVPnbzXQ",
	"FWpaU5m2",
	"FjNCPuiL",
	"Fjo3Ucvj",
	"FpPG1v3f",
	"G5GoMw6y",
	"G6ycYe95",
	"G8VRhszB",
	"G9CQMgwR",
	"GAWgmHjE",
	"GBArDLtL",
	"GBczhVCs",
	"GECxiJX2",
	"GK1TmvD9",
	"GQcc7tC4",
	"GXHhEXzU",
	"GYNQkSV7",
	"GZEAE9UK",
	"GZi9MXvD",
	"GdNu33A8",
	"GqCDebMc",
	"H1SMnTcm",
	"H8T1vSRE",
	"HDG9bk7y",
	"HHspZTti",
	"HM8o367K",
	"HMmnX2dn",
	"HWJhSyFm",
	"HiTeVcZa",
	"HjXhLKdY",
	"HpUMU7MH",
	"Hv4rSQMz",
	"HyEfT7tt",
	"HzTu8vDk",
	"J1MWMdRy",
	"J4ESJSx5",
	"J6h6fhiu",
	"JABDUoso",
	"JAT85AH5",
	"JBMHwwMc",
	"JDfEtnbw",
	"JFT9eGap",
	"JKeKXLws",
	"JLw8sAFk",
	"JMLTcwLm",
	"JNBqjNhw",
	"JQM197G8",
	"JTck5xed",
	"JULCYacN",
	"JYAgz6U9",
	"JbFitpzL",
	"Jm2ScQCY",
	"JpgLT9G5",
	"Jpm2bs9R",
	"K19XcqxJ",
	"K2C9s9GM",
	"K3oyXvVa",
	"K4Cthi6p",
	"K6w6c8DA",
	"KFzoLTPH",
	"KKhPrpmr",
	"KL2p2LAX",
	"KNeq3DaQ",
	"KQ4XrtCz",
	"KSPbZKtF",
	"KWGVK6E6",
	"KXMKiePz",
	"Kcb5asHU",
	"KpDFkdpu",
	"KsBsbMRy",
	"KtZiExmB",
	"KujLFfq7",
	"KxoACnxw",
	"L3ZRQY9h",
	"L6qBtePt",
	"LAe4Mgd4",
	"LBSsubLV",
	"LCyi6BjH",
	"LJyApSwp",
	"LLbKFcVk",
	"LMj62T2q",
	"LSbD9NFP",
	"Lb36KX9e",
	"Lpu9NVEg",
	"Lqh6VPfX",
	"LsqZ58ne",
	"Lvk55nx6",
	"LwjCx2fQ",
	"Lww6PXLJ",
	"LynBmdkd",
	"M2EMVhtk",
	"M48WMebT",
	"M7wWWK8E",
	"M84bKakw",
	"MBNRQtng",
	"MDinqjmR",
	"MRsybTaD",
	"MacGJAQc",
	"MgsKqYTu",
	"MiMCEqwo",
	"Mp4Ushzj",
	"Muk9ta9U",
	"Mux6RrFb",
	"MvwUAedb",
	"Mxh6MFbM",
	"Mzh1Nqzy",
	"N5X6QCsE",
	"N5vRWbND",
	"N9ZREx8s",
	"NATbZAk5",
	"NFU4u856",
	"NK194ofP",
	"NPVzuJMV",
	"NQ6BGC8Z",
	"NReZZCyU",
	"NRoBaTLN",
	"NTrTQhGC",
	"NVHHUn63",
	"NXnvbdF5",
	"NYYUmUoJ",
	"Nhk9rRmm",
	"NiKHQNdp",
	"NrX4nvWX",
	"Nz4ztK9P",
	"PAF7fn9r",
	"PFfERuR6",
	"PGWgMTTz",
	"PHHfjz1Z",
	"PL25UX2Q",
	"PPu1aeSi",
	"PdSwuCcZ",
	"PeSEWywK",
	"PgKQowRK",
	"PhbSG2cx",
	"PjZnvyKi",
	"Pkxjooi9",
	"PrBH2HCz",
	"PuTbmUFL",
	"PuzvUjVK",
	"Pvuqy3uy",
	"PyRu14cF",
	"Q1BtbVm5",
	"Q1u1weCi",
	"QAARcioF",
	"QASzMZHd",
	"QBuYWngZ",
	"QJ9T9rB3",
	"QJKjKxNb",
	"QUeDn53r",
	"QUon6NpY",
	"QV3RwgZw",
	"QXVKErAg",
	"QY1qhw4F",
	"Qb3QLfWk",
	"QcXW14Ye",
	"QdFMRsZe",
	"QjhUCfXy",
	"QuGwb3im",
	"QwCDBnCn",
	"QzLsVqs8",
	"R4zp1Fsf",
	"RJJZiako",
	"RQ7hZXqM",
	"RQzupgYB",
	"RSKJ8Skg",
	"RVrBaenV",
	"RmHpbs6S",
	"RmpwDKd4",
	"RvfSu93z",
	"S3qezWwV",
	"S6id7jqS",
	"S93Fsdky",
	"SACiYUdo",
	"SEapML3R",
	"SHYGDrzg",
	"SJYr4hQf",
	"SK9pdBDj",
	"SMSBnuvD",
	"SMzQzDZi",
	"SNB5uM6c",
	"SPGd5HWC",
	"SV12LH8g",
	"SiMtkxpM",
	"SnEemEEz",
	"SpohvLek",
	"T4shdzmG",
	"TGZVM7A2",
	"TGbDpqGC",
	"THfJ7MXo",
	"TLg2Tuib",
	"TPaTM1F3",
	"TYbc6KGz",
	"TaFhTTUz",
	"Tr2kkGgf",
	"TxPiMPxF",
	"U66S45tG",
	"UKdPBgKv",
	"USmS1HUE",
	"Ua63cFHQ",
	"Ub3jDW2Y",
	"Ug972vQi",
	"UuWNkGUF",
	"Uuo6pK3C",
	"UyYiFGRd",
	"V5bNbNDi",
	"V5foXbJ1",
	"V9LeaLgG",
	"V9YPb2rA",
	"VEBAKXCV",
	"VEzuzCLY",
	"VHc1cvom",
	"VL8yrxHj",
	"VSBM1QFx",
	"VUUWQR7r",
	"VX57oaX6",
	"VXuLk8Ud",
	"VcQvsAtH",
	"Viyfen9s",
	"VmtTRXMZ",
	"VoHpabQY",
	"VvouhhQJ",
	"VwpokJKE",
	"VxdyB74r",
	"VyebyPKR",
	"W1oHStWj",
	"W7AXxcer",
	"W9Bd8R2h",
	"WKK2uFhZ",
	"WMP2eVup",
	"WPMrXC1s",
	"WPR5ANQ4",
	"WUCnu12U",
	"WWGK48hW",
	"WeaTAvYV",
	"Wff32fBV",
	"WknUCyNi",
	"WtHfu49s",
	"Wug9p5Ww",
	"Wvgtdhw5",
	"WxPfsK2d",
	"Wz9TGcf3",
	"XEbbMbLM",
	"XFWqYz5D",
	"XJbz7M9D",
	"XQNdDKSz",
	"XR7K9Sxv",
	"XSce6E2e",
	"XWuXm8Lu",
	"XY6v2kLi",
	"Xf4PsrPT",
	"Xfh2XYxM",
	"XmSw9aLQ",
	"XuUdWbYv",
	"XyDCKkq6",
	"XyxKWqUL",
	"Y3C7cqYs",
	"Y48bJG8e",
	"Y5Sonny8",
	"Y9qgQngR",
	"YLpMRdYo",
	"YMVv5W7Y",
	"YNF1w9Uo",
	"YTXcxyzs",
	"YTzPqHro",
	"YYVykuRT",
	"YYsMVYK8",
	"YZgC3cgq",
	"YcGYa2G4",
	"Z4A22SFN",
	"kBdjyLvz",
	"uLpapnMX",
	"vFnu5EJP",
	"vMc1Szhf",
	"zKPH8SBW",
	"zMM1VH2E",
}

type UUIDHash struct {
	UUID      string
	Hash      int
	TimePoint int
}

func main() {
	mapTimePointUUIDHashs := make(map[int][]*UUIDHash)
	for _, uuid := range uuids {
		value := crcHash(uuid)
		timePoint := value % 60
		uuidHash := &UUIDHash{
			UUID:      uuid,
			Hash:      value,
			TimePoint: timePoint,
		}
		if uuidHashs, found := mapTimePointUUIDHashs[timePoint]; found {
			mapTimePointUUIDHashs[timePoint] = append(mapTimePointUUIDHashs[timePoint], uuidHash)
		} else {
			uuidHashs = make([]*UUIDHash, 0)
			uuidHashs = append(uuidHashs, uuidHash)
			mapTimePointUUIDHashs[timePoint] = uuidHashs
		}
		fmt.Printf("uuidHash: +%v \n", uuidHash)
	}
	for timePoint, UUIDHashs := range mapTimePointUUIDHashs {
		fmt.Printf("timePoint: %d ; len(UUIDHashs): %d\n", timePoint, len(UUIDHashs))
	}
}

func averagedUUIDs() [][]string {
	averageUUIDs := make([][]string, PartCount)
	if len(uuids) <= PartCount {
		for key, uuid := range uuids {
			averageUUIDs[key] = []string{uuid}
		}
	} else {
		part := len(uuids) / PartCount
		remainder := len(uuids) - part*PartCount
		begin := 0
		for i := 0; i < PartCount; i++ {
			if i == PartCount-1 {
				averageUUIDs[i] = uuids[begin:]
			}
			if i < remainder {
				averageUUIDs[i] = uuids[begin : begin+part+1]
				begin = begin + part + 1
			} else {
				averageUUIDs[i] = uuids[begin : begin+part]
				begin = begin + part
			}
		}
	}
	return averageUUIDs
}

func crcHash(s string) int {
	v := int(crc32.ChecksumIEEE([]byte(s)))
	if v >= 0 {
		return v
	}
	if -v >= 0 {
		return -v
	}
	// v == MinInt
	return 0
}
