// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/google/wire"
	"github.com/timliudream/go-test/wireDemo/types"
)

// Injectors from provider.go:

func InitializeEvent(phrase string) (types.Event, error) {
	message := types.NewMessage(phrase)
	greeter := types.NewGreeter(message)
	event, err := types.NewEvent(greeter)
	if err != nil {
		return types.Event{}, err
	}
	return event, nil
}

// provider.go:

var superProvider = wire.NewSet(types.NewMessage, types.NewGreeter, types.NewEvent)
