// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: protofiles/data_streaming/dataStreaming.proto

package data_streaming

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StreamingServiceClient is the client API for StreamingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamingServiceClient interface {
	// unary
	GetDataStreaming(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (StreamingService_GetDataStreamingClient, error)
}

type streamingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamingServiceClient(cc grpc.ClientConnInterface) StreamingServiceClient {
	return &streamingServiceClient{cc}
}

func (c *streamingServiceClient) GetDataStreaming(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (StreamingService_GetDataStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamingService_ServiceDesc.Streams[0], "/protofiles.StreamingService/GetDataStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamingServiceGetDataStreamingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StreamingService_GetDataStreamingClient interface {
	Recv() (*DataResponse, error)
	grpc.ClientStream
}

type streamingServiceGetDataStreamingClient struct {
	grpc.ClientStream
}

func (x *streamingServiceGetDataStreamingClient) Recv() (*DataResponse, error) {
	m := new(DataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamingServiceServer is the server API for StreamingService service.
// All implementations should embed UnimplementedStreamingServiceServer
// for forward compatibility
type StreamingServiceServer interface {
	// unary
	GetDataStreaming(*DataRequest, StreamingService_GetDataStreamingServer) error
}

// UnimplementedStreamingServiceServer should be embedded to have forward compatible implementations.
type UnimplementedStreamingServiceServer struct {
}

func (UnimplementedStreamingServiceServer) GetDataStreaming(*DataRequest, StreamingService_GetDataStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method GetDataStreaming not implemented")
}

// UnsafeStreamingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamingServiceServer will
// result in compilation errors.
type UnsafeStreamingServiceServer interface {
	mustEmbedUnimplementedStreamingServiceServer()
}

func RegisterStreamingServiceServer(s grpc.ServiceRegistrar, srv StreamingServiceServer) {
	s.RegisterService(&StreamingService_ServiceDesc, srv)
}

func _StreamingService_GetDataStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamingServiceServer).GetDataStreaming(m, &streamingServiceGetDataStreamingServer{stream})
}

type StreamingService_GetDataStreamingServer interface {
	Send(*DataResponse) error
	grpc.ServerStream
}

type streamingServiceGetDataStreamingServer struct {
	grpc.ServerStream
}

func (x *streamingServiceGetDataStreamingServer) Send(m *DataResponse) error {
	return x.ServerStream.SendMsg(m)
}

// StreamingService_ServiceDesc is the grpc.ServiceDesc for StreamingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protofiles.StreamingService",
	HandlerType: (*StreamingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDataStreaming",
			Handler:       _StreamingService_GetDataStreaming_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protofiles/data_streaming/dataStreaming.proto",
}
